# Generated by Django 2.1.4 on 2019-01-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_auto_20190109_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='laatst_bijgewerkt',
            field=models.DateTimeField(blank=True, help_text='Datum en tijd van wanneer het object voor het laatst is bijgewerkt.', null=True, verbose_name='laatst bijgewerkt'),
        ),
    ]
